const dataOperationsContext = [
    {
        'addition': [
            'mais',
            'adicionado',
            'somado',
            'inserido',
            'incluido',
            'incluído',
            'aumentado',
            'incorporado',
            'agregado',
            'insertado',
            'adicionar',
            'somar',
            'aumentar',
            'incluir'
        ],

        'subtraction': [
            'menos',
            'subtraído',
            'subtraido',
            'removido',
            'diminuido',
            'tirado',
            'retirado',
            'subtrair',
            'omitir',
            'roubar',
            'elidir',
            'encobrir',
            'excluir',
            'expungir',
            'suprimir',
            'ocultar',
            'abafar',
            'afanar',
            'arrebatar',
            'bifar',
            'defraudar',
            'depenar',
            'desfalcar',
            'despojar',
            'escorchar',
            'furtar',
            'gadunhar',
            'gatunar',
            'ladroar',
            'levar',
            'pilhar',
            'rapar',
            'rapinar',
            'raptar',
            'saquear',
            'surripiar',
            'surrupiar',
            'tirar',
            'desanexar',
            'desapensar',
            'desapor',
            'desincorporar',
            'desprender',
            'separar',
            'abater',
            'decrescer',
            'deduzir',
            'diminuir',
            'reduzir',
            'retirar',
            'deixando',
            'omitindo',
            'suprimindo',
            'eliminando',
            'apagando',
            'esquecendo',
            'desconsiderando',
            'desprezando',
            'ignorando',
            'desatendendo',
            'abstraindo',
            'retirando',
            'tirando',
            'arrebatando',
            'roubando',
            'furtando',
            'recolhendo',
            'usurpando',
            'confiscando',
            'capturando',
            'arrestando',
            'emprestando'
        ],

        'multiplication': [
            'vezes',
            'multiplicado',
            'multiplicar'
        ],

        'division': [
            'dividido',
            'sobre',
            'fracionado',
            'particionar',
            'particionado',
            'distribuido',
            'distribuir',
        ],

        'potentiation': [
            'elevado'
        ]
    }
]

module.exports = dataOperationsContext
